sonar.organization=kloudways
sonar.projectKey=kloudways_pacemoney-app
sonar.projectName=Pace Money
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml
