replicaCount: 2

image:
  repository: 684779207098.dkr.ecr.eu-west-2.amazonaws.com/pacemoney
  tag: c3c7f4a
  pullPolicy: IfNotPresent

app:
  port: 8000

externalSecret:
  region: eu-west-2
  secretName: pacemoney/db-url

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

service:
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
