apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacemoney
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.io
spec:
  project: default
  source:
    repoURL: https://github.com/kloudways/pacemoney-app.git
    targetRevision: main
    path: deploy/helm/pacemoney
    helm:
      valueFiles:
        - values.yaml
        - values.prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: pacemoney
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
