apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "pacemoney.fullname" . }}-db
  labels:
    {{- include "pacemoney.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "pacemoney.fullname" . }}-aws
    kind: SecretStore
  target:
    name: {{ include "pacemoney.fullname" . }}-db
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecret.secretName }}
