{{- if .Values.database.url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pacemoney.fullname" . }}-db
  labels:
    {{- include "pacemoney.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
{{- end }}
