apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pacemoney.fullname" . }}
  labels:
    {{- include "pacemoney.labels" . | nindent 4 }}
    release: monitoring
spec:
  selector:
    matchLabels:
      {{- include "pacemoney.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
